from fpdf import FPDF
from datetime import datetime


def generate_report(
    ats_score,
    match_score,
    matched_skills,
    missing_skills,
    recommendations
):
    ats_score = round(float(ats_score), 2)
    match_score = round(float(match_score), 2)

    pdf = FPDF()
    pdf.add_page()
    pdf.set_auto_page_break(auto=True, margin=15)

    # =====================================
    # HEADER
    # =====================================
    pdf.set_font("Helvetica", "B", 20)
    pdf.cell(
        0,
        12,
        "AI RESUME ANALYZER REPORT",
        new_x="LMARGIN",
        new_y="NEXT",
        align="C"
    )

    pdf.set_font("Helvetica", "", 11)
    pdf.cell(
        0,
        8,
        f"Generated on {datetime.now().strftime('%d %B %Y')}",
        new_x="LMARGIN",
        new_y="NEXT",
        align="C"
    )

    pdf.ln(5)

    # =====================================
    # SUMMARY BOX
    # =====================================
    pdf.set_font("Helvetica", "B", 14)
    pdf.cell(
        0,
        8,
        "CANDIDATE SUMMARY",
        new_x="LMARGIN",
        new_y="NEXT"
    )

    pdf.rect(10, pdf.get_y(), 190, 30)

    start_y = pdf.get_y() + 4

    pdf.set_xy(15, start_y)

    if ats_score >= 80:
        status = "Excellent"
    elif ats_score >= 60:
        status = "Good"
    else:
        status = "Needs Improvement"

    pdf.set_font("Helvetica", "", 12)

    pdf.cell(0, 6, f"ATS Score       : {ats_score}/100", new_x="LMARGIN", new_y="NEXT")
    pdf.cell(0, 6, f"Resume Match    : {match_score}%", new_x="LMARGIN", new_y="NEXT")
    pdf.cell(0, 6, f"Status          : {status}", new_x="LMARGIN", new_y="NEXT")

    pdf.ln(10)

    # =====================================
    # PROGRESS BARS
    # =====================================
    pdf.set_font("Helvetica", "B", 14)
    pdf.cell(
        0,
        8,
        "PERFORMANCE OVERVIEW",
        new_x="LMARGIN",
        new_y="NEXT"
    )

    pdf.set_font("Courier", "", 11)

    ats_bar = "█" * int(ats_score / 10) + "░" * (10 - int(ats_score / 10))
    match_bar = "█" * int(match_score / 10) + "░" * (10 - int(match_score / 10))

    pdf.cell(
        0,
        8,
        f"ATS Score      [{ats_bar}] {ats_score}%",
        new_x="LMARGIN",
        new_y="NEXT"
    )

    pdf.cell(
        0,
        8,
        f"Resume Match   [{match_bar}] {match_score}%",
        new_x="LMARGIN",
        new_y="NEXT"
    )

    pdf.ln(5)

    # =====================================
    # MATCHED SKILLS
    # =====================================
    pdf.set_font("Helvetica", "B", 14)

    pdf.cell(
        0,
        8,
        f"MATCHED SKILLS ({len(matched_skills)})",
        new_x="LMARGIN",
        new_y="NEXT"
    )

    pdf.set_font("Helvetica", "", 11)

    matched_text = " | ".join(matched_skills)

    pdf.multi_cell(
        0,
        8,
        matched_text
    )

    pdf.ln(3)

    # =====================================
    # MISSING SKILLS
    # =====================================
    pdf.set_font("Helvetica", "B", 14)

    pdf.cell(
        0,
        8,
        f"MISSING SKILLS ({len(missing_skills)})",
        new_x="LMARGIN",
        new_y="NEXT"
    )

    pdf.set_font("Helvetica", "", 11)

    if missing_skills:
        missing_text = " | ".join(missing_skills)
        pdf.multi_cell(
            0,
            8,
            missing_text
        )
    else:
        pdf.multi_cell(
            0,
            8,
            "No missing skills detected."
        )

    pdf.ln(3)

    # =====================================
    # RECOMMENDATIONS
    # =====================================
    pdf.set_font("Helvetica", "B", 14)

    pdf.cell(
        0,
        8,
        "RECOMMENDATIONS",
        new_x="LMARGIN",
        new_y="NEXT"
    )

    pdf.set_font("Helvetica", "", 11)

    for i, recommendation in enumerate(recommendations, 1):

        clean_text = (
            str(recommendation)
            .replace("✓", "")
            .replace("✗", "")
            .replace("•", "")
            .replace("✔", "")
            .replace("❌", "")
        )

        pdf.multi_cell(
            0,
            8,
            f"{i}. {clean_text}"
        )

    pdf.ln(5)

    # =====================================
    # FOOTER
    # =====================================
    pdf.set_font("Helvetica", "I", 10)

    pdf.cell(
        0,
        8,
        "Generated by AI Resume Analyzer",
        new_x="LMARGIN",
        new_y="NEXT",
        align="C"
    )

    file_name = "resume_report.pdf"

    pdf.output(file_name)

    return file_name