from fpdf import FPDF
from datetime import datetime


def generate_report(
    ats_score,
    match_score,
    matched_skills,
    missing_skills,
    recommendations
):
    ats_score = round(float(ats_score), 2)
    match_score = round(float(match_score), 2)

    pdf = FPDF()
    pdf.add_page()
    pdf.set_auto_page_break(auto=True, margin=15)

    # ==========================
    # TITLE
    # ==========================
    pdf.set_font("Helvetica", "B", 18)
    pdf.cell(
        0,
        12,
        "AI Resume Analyzer Report",
        new_x="LMARGIN",
        new_y="NEXT",
        align="C"
    )

    pdf.set_font("Helvetica", "", 11)
    pdf.cell(
        0,
        8,
        f"Generated on: {datetime.now().strftime('%d %B %Y')}",
        new_x="LMARGIN",
        new_y="NEXT",
        align="C"
    )

    pdf.ln(5)

    # ==========================
    # OVERALL SUMMARY
    # ==========================
    pdf.set_font("Helvetica", "B", 14)
    pdf.cell(
        0,
        8,
        "OVERALL SUMMARY",
        new_x="LMARGIN",
        new_y="NEXT"
    )

    pdf.line(10, pdf.get_y(), 200, pdf.get_y())
    pdf.ln(4)

    if ats_score >= 80:
        status = "Excellent"
    elif ats_score >= 60:
        status = "Good"
    else:
        status = "Needs Improvement"

    pdf.set_font("Helvetica", "", 12)

    pdf.cell(
        0,
        8,
        f"ATS Score: {ats_score}/100",
        new_x="LMARGIN",
        new_y="NEXT"
    )

    pdf.cell(
        0,
        8,
        f"Resume Match: {match_score}%",
        new_x="LMARGIN",
        new_y="NEXT"
    )

    pdf.cell(
        0,
        8,
        f"Status: {status}",
        new_x="LMARGIN",
        new_y="NEXT"
    )

    pdf.ln(5)

    # ==========================
    # MATCHED SKILLS
    # ==========================
    pdf.set_font("Helvetica", "B", 14)
    pdf.cell(
        0,
        8,
        "MATCHED SKILLS",
        new_x="LMARGIN",
        new_y="NEXT"
    )

    pdf.line(10, pdf.get_y(), 200, pdf.get_y())
    pdf.ln(4)

    pdf.set_font("Helvetica", "", 12)

    if matched_skills:
        for skill in matched_skills:
            pdf.cell(
                0,
                8,
                f"- {skill}",
                new_x="LMARGIN",
                new_y="NEXT"
            )
    else:
        pdf.cell(
            0,
            8,
            "No matched skills found.",
            new_x="LMARGIN",
            new_y="NEXT"
        )

    pdf.ln(5)

    # ==========================
    # MISSING SKILLS
    # ==========================
    pdf.set_font("Helvetica", "B", 14)
    pdf.cell(
        0,
        8,
        "MISSING SKILLS",
        new_x="LMARGIN",
        new_y="NEXT"
    )

    pdf.line(10, pdf.get_y(), 200, pdf.get_y())
    pdf.ln(4)

    pdf.set_font("Helvetica", "", 12)

    if missing_skills:
        for skill in missing_skills:
            pdf.cell(
                0,
                8,
                f"- {skill}",
                new_x="LMARGIN",
                new_y="NEXT"
            )
    else:
        pdf.cell(
            0,
            8,
            "No missing skills detected.",
            new_x="LMARGIN",
            new_y="NEXT"
        )

    pdf.ln(5)

    # ==========================
    # RECOMMENDATIONS
    # ==========================
    pdf.set_font("Helvetica", "B", 14)
    pdf.cell(
        0,
        8,
        "RECOMMENDATIONS",
        new_x="LMARGIN",
        new_y="NEXT"
    )

    pdf.line(10, pdf.get_y(), 200, pdf.get_y())
    pdf.ln(4)

    pdf.set_font("Helvetica", "", 12)

    if recommendations:
        for recommendation in recommendations:

            clean_text = (
                str(recommendation)
                .replace("✓", "")
                .replace("✗", "")
                .replace("•", "")
                .replace("✔", "")
                .replace("❌", "")
            )

            pdf.cell(
                0,
                8,
                f"- {clean_text}",
                new_x="LMARGIN",
                new_y="NEXT"
            )

    else:
        pdf.cell(
            0,
            8,
            "Your resume aligns well with the job description.",
            new_x="LMARGIN",
            new_y="NEXT"
        )

    pdf.ln(8)

    # ==========================
    # FOOTER
    # ==========================
    pdf.set_font("Helvetica", "I", 10)

    pdf.cell(
        0,
        8,
        "Generated by AI Resume Analyzer",
        new_x="LMARGIN",
        new_y="NEXT",
        align="C"
    )

    file_name = "resume_report.pdf"
    pdf.output(file_name)

    return file_name